# CMake generated Testfile for 
# Source directory: /home/hugo/Desktop/emp/emp-sh2pc/test
# Build directory: /home/hugo/Desktop/emp/emp-sh2pc/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(bit "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_bit")
set_tests_properties(bit PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;19;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(int "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_int")
set_tests_properties(int PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;20;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(circuit_file "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_circuit_file")
set_tests_properties(circuit_file PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;24;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(example "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_example")
set_tests_properties(example PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;25;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(repeat "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_repeat")
set_tests_properties(repeat PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;26;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_with_state "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_with_state")
set_tests_properties(sha256_with_state PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;27;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha-256 "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha-256")
set_tests_properties(sha-256 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;28;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_padded "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_padded")
set_tests_properties(sha256_padded PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;29;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_i_2_share_msg_1_state_o_hash_state "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_i_2_share_msg_1_state_o_hash_state")
set_tests_properties(sha256_i_2_share_msg_1_state_o_hash_state PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;30;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_i_2_share_msg_2_mask_1_state_o_2_share "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_i_2_share_msg_2_mask_1_state_o_2_share")
set_tests_properties(sha256_i_2_share_msg_2_mask_1_state_o_2_share PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;31;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(innerproduct "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_innerproduct")
set_tests_properties(innerproduct PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;32;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_input_two_state "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_input_two_state")
set_tests_properties(sha256_input_two_state PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;33;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_input_two_state_trunc "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_input_two_state_trunc")
set_tests_properties(sha256_input_two_state_trunc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;34;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_input_two_state_trunc_320 "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_input_two_state_trunc_320")
set_tests_properties(sha256_input_two_state_trunc_320 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;35;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_input_two_state_trunc_96 "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_input_two_state_trunc_96")
set_tests_properties(sha256_input_two_state_trunc_96 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;36;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(sha256_input_two_state_trunc_wo_hash "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_sha256_input_two_state_trunc_wo_hash")
set_tests_properties(sha256_input_two_state_trunc_wo_hash PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;37;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(xor "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_xor")
set_tests_properties(xor PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;38;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(condition "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_condition")
set_tests_properties(condition PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;39;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(GFMult128 "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_GFMult128")
set_tests_properties(GFMult128 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;40;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(predicate_ghash "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_predicate_ghash")
set_tests_properties(predicate_ghash PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;41;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(dec_ghash "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_dec_ghash")
set_tests_properties(dec_ghash PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;42;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(input_test "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_input_test")
set_tests_properties(input_test PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;43;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(MtA_1 "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_MtA_1")
set_tests_properties(MtA_1 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;44;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(hex2Int "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_hex2Int")
set_tests_properties(hex2Int PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;45;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(add2xor "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_add2xor")
set_tests_properties(add2xor PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;46;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(enc_ghash "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_enc_ghash")
set_tests_properties(enc_ghash PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;47;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(predicate_enc_ghash "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_predicate_enc_ghash")
set_tests_properties(predicate_enc_ghash PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;48;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(aes "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_aes")
set_tests_properties(aes PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;49;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_aes_gcm")
set_tests_properties(aes_gcm PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;50;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_dec "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_aes_gcm_dec")
set_tests_properties(aes_gcm_dec PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;51;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(predicate_aes_gcm "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_predicate_aes_gcm")
set_tests_properties(predicate_aes_gcm PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;52;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
add_test(relu "./run" "/home/hugo/Desktop/emp/emp-sh2pc/bin/test_relu")
set_tests_properties(relu PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-sh2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;53;add_test_case_with_run;/home/hugo/Desktop/emp/emp-sh2pc/test/CMakeLists.txt;0;")
