# CMake generated Testfile for 
# Source directory: /home/hugo/Desktop/emp/emp-tool/test
# Build directory: /home/hugo/Desktop/emp/emp-tool/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(prg "/home/hugo/Desktop/emp/emp-tool/bin/test_prg")
set_tests_properties(prg PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;20;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(hash "/home/hugo/Desktop/emp/emp-tool/bin/test_hash")
set_tests_properties(hash PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;21;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(prp "/home/hugo/Desktop/emp/emp-tool/bin/test_prp")
set_tests_properties(prp PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;22;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(netio "/home/hugo/Desktop/emp/emp-tool/run" "/home/hugo/Desktop/emp/emp-tool/bin/test_netio")
set_tests_properties(netio PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;23;add_test_case_with_run;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(netio2 "/home/hugo/Desktop/emp/emp-tool/run" "/home/hugo/Desktop/emp/emp-tool/bin/test_netio2")
set_tests_properties(netio2 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;24;add_test_case_with_run;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(bit "/home/hugo/Desktop/emp/emp-tool/bin/test_bit")
set_tests_properties(bit PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;25;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(ecc "/home/hugo/Desktop/emp/emp-tool/bin/test_ecc")
set_tests_properties(ecc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;26;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(int "/home/hugo/Desktop/emp/emp-tool/bin/test_int")
set_tests_properties(int PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;27;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(float "/home/hugo/Desktop/emp/emp-tool/bin/test_float")
set_tests_properties(float PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;28;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(garble "/home/hugo/Desktop/emp/emp-tool/run" "/home/hugo/Desktop/emp/emp-tool/bin/test_garble")
set_tests_properties(garble PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;29;add_test_case_with_run;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(gen_circuit "/home/hugo/Desktop/emp/emp-tool/bin/test_gen_circuit")
set_tests_properties(gen_circuit PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;30;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(mitccrh "/home/hugo/Desktop/emp/emp-tool/bin/test_mitccrh")
set_tests_properties(mitccrh PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;31;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(f2k "/home/hugo/Desktop/emp/emp-tool/bin/test_f2k")
set_tests_properties(f2k PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;32;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(halfgate "/home/hugo/Desktop/emp/emp-tool/bin/test_halfgate")
set_tests_properties(halfgate PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;33;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(to_bool "/home/hugo/Desktop/emp/emp-tool/bin/test_to_bool")
set_tests_properties(to_bool PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;34;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
add_test(aes_opt "/home/hugo/Desktop/emp/emp-tool/bin/test_aes_opt")
set_tests_properties(aes_opt PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-tool/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;9;add_test;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;35;add_test_case;/home/hugo/Desktop/emp/emp-tool/test/CMakeLists.txt;0;")
