# CMake generated Testfile for 
# Source directory: /home/hugo/Desktop/emp/emp-ag2pc/test
# Build directory: /home/hugo/Desktop/emp/emp-ag2pc/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(aes "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes")
set_tests_properties(aes PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;19;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(sha1 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_sha1")
set_tests_properties(sha1 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;20;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(sha256 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_sha256")
set_tests_properties(sha256 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;21;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(simple_circuit "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_simple_circuit")
set_tests_properties(simple_circuit PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;22;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(abit "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_abit")
set_tests_properties(abit PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;23;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(triple "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_triple")
set_tests_properties(triple PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;24;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(amortized_2pc "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_amortized_2pc")
set_tests_properties(amortized_2pc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;25;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_mult_inputs "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_mult_inputs")
set_tests_properties(aes_mult_inputs PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;26;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(KDF_384 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_KDF_384")
set_tests_properties(KDF_384 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;27;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(KDF_448 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_KDF_448")
set_tests_properties(KDF_448 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;28;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(sha256_output_two "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_sha256_output_two")
set_tests_properties(sha256_output_two PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;29;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(innerproduct "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_innerproduct")
set_tests_properties(innerproduct PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;30;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(xor "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_xor")
set_tests_properties(xor PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;31;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(addition "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_addition")
set_tests_properties(addition PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;32;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(condition "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_condition")
set_tests_properties(condition PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;33;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(GFMult128 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_GFMult128")
set_tests_properties(GFMult128 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;34;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_enc "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_gcm_enc")
set_tests_properties(aes_gcm_enc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;35;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_dec "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_gcm_dec")
set_tests_properties(aes_gcm_dec PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;36;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_enc_record "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_gcm_enc_record")
set_tests_properties(aes_gcm_enc_record PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;37;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(predicate_aes_gcm_enc_record "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_predicate_aes_gcm_enc_record")
set_tests_properties(predicate_aes_gcm_enc_record PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;38;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_dec_record "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_gcm_dec_record")
set_tests_properties(aes_gcm_dec_record PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;39;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_enc_cf "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_gcm_enc_cf")
set_tests_properties(aes_gcm_enc_cf PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;40;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes_gcm_dec_sf "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes_gcm_dec_sf")
set_tests_properties(aes_gcm_dec_sf PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;41;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(input_test "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_input_test")
set_tests_properties(input_test PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;42;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(add2xor "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_add2xor")
set_tests_properties(add2xor PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;43;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(add2xor-p256 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_add2xor-p256")
set_tests_properties(add2xor-p256 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;44;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(p256-ectf "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_p256-ectf")
set_tests_properties(p256-ectf PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;45;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(tls-prf-384 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_tls-prf-384")
set_tests_properties(tls-prf-384 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;46;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(tls-prf-320 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_tls-prf-320")
set_tests_properties(tls-prf-320 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;47;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(tls-prf-320-shares "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_tls-prf-320-shares")
set_tests_properties(tls-prf-320-shares PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;48;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(tls-prf-320-2-shares "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_tls-prf-320-2-shares")
set_tests_properties(tls-prf-320-2-shares PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;49;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(tls-prf-96 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_tls-prf-96")
set_tests_properties(tls-prf-96 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;50;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(tls-prf-96-sf "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_tls-prf-96-sf")
set_tests_properties(tls-prf-96-sf PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;51;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(test_prf_96 "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_test_prf_96")
set_tests_properties(test_prf_96 PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;52;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(test_aes "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_test_aes")
set_tests_properties(test_aes PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;53;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes-gcm-2pc "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes-gcm-2pc")
set_tests_properties(aes-gcm-2pc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;54;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(aes-gcm-dec-2pc "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_aes-gcm-dec-2pc")
set_tests_properties(aes-gcm-dec-2pc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;55;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
add_test(predicate-aes-gcm-2pc "./run" "/home/hugo/Desktop/emp/emp-ag2pc/bin/test_predicate-aes-gcm-2pc")
set_tests_properties(predicate-aes-gcm-2pc PROPERTIES  WORKING_DIRECTORY "/home/hugo/Desktop/emp/emp-ag2pc/" _BACKTRACE_TRIPLES "/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;14;add_test;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;56;add_test_case_with_run;/home/hugo/Desktop/emp/emp-ag2pc/test/CMakeLists.txt;0;")
